// 13-react/01-react基础/day02/myapp/src/components/AddTodo.js
import React from 'react';
import PropTypes from "prop-types"

export default class AddTodo extends React.Component {
    static propTypes = {
		addTodo:PropTypes.func.isRequired 
	}
    handleKeyUp(e){
        let content = e.target.value.trim();
        if(!content) return;
        if(e.keyCode === 13){
            this.props.addTodo({content,complete:false})
            e.target.value = "";
        }
    }
    render() {
        return (
            <header className="header">
                <h1>todos</h1>
                <input type="text" placeholder="what need to be done?" className="new-todo" onKeyUp={this.handleKeyUp.bind(this)}/>
            </header>
        );
    }
}

// 12-vue复习和项目/bak/02-day01todomvc/src/components/AddTodo.vue
<template>
  <header class="header">
    <h1>todos</h1>
    <!-- v-model 也有一些修饰符 trim  lazy -->
    <input type="text" v-model.trim.lazy="txt" 
        placeholder="what need to be done?" class="new-todo" 
        @keyup.enter="add"
    />
  </header>
</template>
<script>
import { mapMutations } from "vuex"
export default {
    data(){
        return{
            txt:""
        }
    },
    methods: {
        ...mapMutations(["addTodo"]),
        add(){
            this.addTodo(this.txt)
            this.txt = ""
        }
    }
};
</script>
